### ISSUE TITLE
ENV instead

### ISSUE THREAD

**Issue by thpallround** [CM2Walki/Mordhau#2]
Is'nt it better to use the ENV variables fom the upper lines?

https://github.com/CM2Walki/Mordhau/blob/860aec78187338b0eed82950ecdea50086ae6c1b/stretch/Dockerfile#L111

**Comment by CM2Walki** [comment]
Fair point.
I'm unable to track down an official image that handles ports & environmental variables that way though (I try to stick to their syntax as much as I can, if you find one let me know). 

I was able to find an issue of stackoverflow regarding this though, and [this bloke](https://stackoverflow.com/questions/50178013/docker-expose-using-run-time-environment-variables) appears to have had issues replacing the variables in _docker run_ when using that syntax.

Bottom line, I usually just put _EXPOSE_ in the dockerfile for documentation purposes. From the [official docker documentation](https://docs.docker.com/engine/reference/builder/):
"The EXPOSE instruction does not actually publish the port. It functions as a type of documentation between the person who builds the image and the person who runs the container, about which ports are intended to be published."
As an example, nginx and httpd are both using _EXPOSE 80_, but then they don't define a variable that could potentially override it. However, then again a lot of people run webservers on other ports using _--publish=_.
