### ISSUE TITLE
High ping in server browser only

### ISSUE THREAD

**Issue by script1542** [CM2Walki/Mordhau#9]
I'm hosting a Mordhau server container in Israel, which is in the Middle East.
When viewing the server through the server browser, it is reported to as 80-150ms.
When connected to the server - in game, I'm getting a respectable ping of 8-12ms.
I can only speculate that my server reports back to Europe or America.
Is there perhaps a way to set my server to report ping to a nearer server?

Huge thanks for you work!

**Comment by CM2Walki** [comment]
This is not related to this image. It seems to be related to the master server of Mordhau (maybe it's doing ping checks from NA or Europe).
